### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by der-On** [gjtorikian/markdowntutorial.com#12]
This is a great ressource for new markdown writers. However I would love to translate it. Is there a way of making it translatable? If not I will simply fork it and create a new branch for my language.

**Comment by 5y** [comment]
@gjtorikian Good and Clear resource, i would translate it too.

**Comment by codingnuri** [comment]
This tutorial is great for learning Markdown for beginners. I'd like to know if I can translate it and upload in my web site. :)

**Comment by nicolasmccurdy** [comment]
@codingnuri What was your issue?

**Comment by codingnuri** [comment]
@nicolasmccurdy Though I installed the jekyll-coffeescript gem, but I got this error.

Dependency Error: Yikes! It looks like you don't have jekyll-coffeescript or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-coffeescript' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
jekyll 3.1.5 | Error:  jekyll-coffeescript

**Comment by codingnuri** [comment]
@nicolasmccurdy I solved this problem by trying `bundle exec jekyll serve`. Thanks anyway! 👍

**Comment by victorhck** [comment]
What happened with translations?
Finally are not available?

**Comment by gjtorikian** [comment]
No one seemed to contribute any.

**Comment by victorhck** [comment]
der-On didn't make a German Translation?
How could I collaborate to a Spanish version? I tried to deploy a GitLab pages with a Spanish version cloning this repository, but there are some issues that don't know how to solve... and was looking how to try to translate this resource.

**Comment by victorhck** [comment]
I  did it :)
Thank to you

**Comment by seahindeniz** [comment]
Hey @gjtorikian  !
You have a very good project! As a foreigners, I would like to participate by translating too :)

Other than PR request, I would suggest you to use a translating platform such as Transifex. Just open a account and start a new project on Transifex and invite translators to your project. I feel like most people can participate the translation program.
That kind of translation platforms are very easy to use and handling and managing new or old strings is very easy.

But you need to setup your system to this too..
You can use their API services or you can download translated language files from the translating platform and include it on your project.

Also, you can choose Transifex. They have currently free support for open source projects.
I also had a free invitation from POEditor because since I know, they also have free support for OS projects, but I suggest Transifex, it's very easy to use and invite others.

**Comment by offray** [comment]
Hi, I have not seen the Spanish translation. If this is fine, I would like to volunteer for it. I will try to provide the translation strings in a friendly format, so I will start to review how YAML is being used in the Ruby project. Once translation is done in such format, should be really easy to translate to JSON or others.

Thanks for Markdown Tutorial.

**Comment by victorhck** [comment]
I made a PR #63 with spanish translation

**Comment by offray** [comment]
Yes, I just found it. Thanks! I will try to see if I can load your branch to test it locally.

**Comment by gjtorikian** [comment]
Oh dang, I missed it again, even after I said "I missed this."

I will look right now.

**Comment by victorhck** [comment]
you missed again?? :)

**Comment by victorhck** [comment]
no news, good news?
there's something more I can help?

**Comment by victorhck** [comment]
> 
> 
> Oh dang, I missed it again, even after I said "I missed this."
> 
> I will look right now.

you missed again??

**Comment by gjtorikian** [comment]
Closed via https://github.com/gjtorikian/markdowntutorial.com/pull/63. If anyone wants to add more translations I'd be happy to merge them much quicker than years.
