### ISSUE TITLE
Second exercise in Lesson 6

### ISSUE THREAD

**Issue by cliffvick** [gjtorikian/markdowntutorial.com#37]
The criteria for continuing on to the next exercise in the lesson is incorrect in the js/lesson_plans.coffee file (line 69).  The provided text omits the periods, but the lesson plan expects a period after each item.

**Comment by gjtorikian** [comment]
Thanks for the report. The provided text *should* omit the periods, since it's initially a sequence with commas:

![screen shot 2014-12-31 at 5 02 45 pm](https://cloud.githubusercontent.com/assets/64050/5591410/ddcaf0d6-910e-11e4-8f69-e496814afb5d.png)

As it's a list of proper sentences, you create the ordered list, and then provide periods:

![screen shot 2014-12-31 at 5 02 31 pm](https://cloud.githubusercontent.com/assets/64050/5591411/e874c764-910e-11e4-9206-31ca6b39bda9.png)

Hope that helps. Please feel free to reopen if I've missed something. Happy new year!

**Comment by cliffvick** [comment]
While you are technically correct in your assessment, none of your other examples have this particular problem.  If this were a grammar and/or punctuation tutorial I might agree with you, but this is a markdown tutorial, and this caused quite a bit of confusion for me.  I had to look at the source to figure out that there should be periods there, which really has nothing to do with getting to the next part in the tutorial.

**Comment by gjtorikian** [comment]
Fair enough; [this isn't the first case of this](https://github.com/gjtorikian/markdowntutorial.com/issues/28). I'll fix and push when I get a chance.

**Comment by cliffvick** [comment]
I do know how you feel - I die a little inside when I hear someone say, "supposebly".  Apologies for being so thick!

Thanks :)

Cliff
